backend:
  namespace: kodlnw-service-uat
  image: ghcr.io/kodlnw-software-house/back-end-service
  tag: uat
  replicas: 1
  imagePullSecrets: kodlnw-registry
  port: 2083
  healthCheckPath: "/health"
ingress:
  host: uat.kodlnw-product.net
  path: "/back-end(/|$)(.*)"
  serviceType: ClusterIP
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
extraEnv:
  ENV_HOST: kodlnw-service-front-end-uat