backend:
  namespace: kodlnw-service-dev
  image: ghcr.io/kodlnw-software-house/back-end-service
  tag: dev
  replicas: 1
  imagePullSecrets: kodlnw-registry
  port: 8082
  healthCheckPath: "/health"
ingress:
  host: dev.kodlnw-product.net
  path: "/back-end(/|$)(.*)"
  serviceType: ClusterIP
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2