backend:
  namespace: kodlnw-service-dev
  image: ghcr.io/kodlnw-software-house/back-end-service
  tag: dev
  replicas: 1
  imagePullSecrets: kodlnw-registry
  port: 8880
  healthCheckPath: "/health"
ingress:
  host: dev.backend.ingress.kodlnw-product.net
  path: "/"
  serviceType: ClusterIP
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
extraEnv:
  ENV_HOST: kodlnw-service-front-end-dev
